/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedViewServicesRouteImport } from './routes/_protected/view-services'
import { Route as ProtectedViewProfileRouteImport } from './routes/_protected/view-profile'
import { Route as ProtectedRegisterServiceRouteImport } from './routes/_protected/register-service'
import { Route as ProtectedLogoutRouteImport } from './routes/_protected/logout'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as PublicAuthLoginRouteImport } from './routes/_public/auth/login'
import { Route as ProtectedAdminViewUsersRouteImport } from './routes/_protected/admin/view-users'
import { Route as ProtectedAdminViewGroupsRouteImport } from './routes/_protected/admin/view-groups'
import { Route as ProtectedAdminCreateUserRouteImport } from './routes/_protected/admin/create-user'
import { Route as ProtectedAdminCreateGroupRouteImport } from './routes/_protected/admin/create-group'
import { Route as ProtectedAdminAddGroupServiceRouteImport } from './routes/_protected/admin/add-group-service'
import { Route as ProtectedAdminAddGroupMemberRouteImport } from './routes/_protected/admin/add-group-member'
import { Route as PublicAuthRegistrationRegistrationIdRouteImport } from './routes/_public/auth/registration/$registrationId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedViewServicesRoute = ProtectedViewServicesRouteImport.update({
  id: '/view-services',
  path: '/view-services',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedViewProfileRoute = ProtectedViewProfileRouteImport.update({
  id: '/view-profile',
  path: '/view-profile',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRegisterServiceRoute =
  ProtectedRegisterServiceRouteImport.update({
    id: '/register-service',
    path: '/register-service',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedLogoutRoute = ProtectedLogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const PublicAuthLoginRoute = PublicAuthLoginRouteImport.update({
  id: '/_public/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdminViewUsersRoute = ProtectedAdminViewUsersRouteImport.update({
  id: '/admin/view-users',
  path: '/admin/view-users',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminViewGroupsRoute =
  ProtectedAdminViewGroupsRouteImport.update({
    id: '/admin/view-groups',
    path: '/admin/view-groups',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminCreateUserRoute =
  ProtectedAdminCreateUserRouteImport.update({
    id: '/admin/create-user',
    path: '/admin/create-user',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminCreateGroupRoute =
  ProtectedAdminCreateGroupRouteImport.update({
    id: '/admin/create-group',
    path: '/admin/create-group',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminAddGroupServiceRoute =
  ProtectedAdminAddGroupServiceRouteImport.update({
    id: '/admin/add-group-service',
    path: '/admin/add-group-service',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdminAddGroupMemberRoute =
  ProtectedAdminAddGroupMemberRouteImport.update({
    id: '/admin/add-group-member',
    path: '/admin/add-group-member',
    getParentRoute: () => ProtectedRoute,
  } as any)
const PublicAuthRegistrationRegistrationIdRoute =
  PublicAuthRegistrationRegistrationIdRouteImport.update({
    id: '/_public/auth/registration/$registrationId',
    path: '/auth/registration/$registrationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/logout': typeof ProtectedLogoutRoute
  '/register-service': typeof ProtectedRegisterServiceRoute
  '/view-profile': typeof ProtectedViewProfileRoute
  '/view-services': typeof ProtectedViewServicesRoute
  '/admin/add-group-member': typeof ProtectedAdminAddGroupMemberRoute
  '/admin/add-group-service': typeof ProtectedAdminAddGroupServiceRoute
  '/admin/create-group': typeof ProtectedAdminCreateGroupRoute
  '/admin/create-user': typeof ProtectedAdminCreateUserRoute
  '/admin/view-groups': typeof ProtectedAdminViewGroupsRoute
  '/admin/view-users': typeof ProtectedAdminViewUsersRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/registration/$registrationId': typeof PublicAuthRegistrationRegistrationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/logout': typeof ProtectedLogoutRoute
  '/register-service': typeof ProtectedRegisterServiceRoute
  '/view-profile': typeof ProtectedViewProfileRoute
  '/view-services': typeof ProtectedViewServicesRoute
  '/admin/add-group-member': typeof ProtectedAdminAddGroupMemberRoute
  '/admin/add-group-service': typeof ProtectedAdminAddGroupServiceRoute
  '/admin/create-group': typeof ProtectedAdminCreateGroupRoute
  '/admin/create-user': typeof ProtectedAdminCreateUserRoute
  '/admin/view-groups': typeof ProtectedAdminViewGroupsRoute
  '/admin/view-users': typeof ProtectedAdminViewUsersRoute
  '/auth/login': typeof PublicAuthLoginRoute
  '/auth/registration/$registrationId': typeof PublicAuthRegistrationRegistrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/logout': typeof ProtectedLogoutRoute
  '/_protected/register-service': typeof ProtectedRegisterServiceRoute
  '/_protected/view-profile': typeof ProtectedViewProfileRoute
  '/_protected/view-services': typeof ProtectedViewServicesRoute
  '/_protected/admin/add-group-member': typeof ProtectedAdminAddGroupMemberRoute
  '/_protected/admin/add-group-service': typeof ProtectedAdminAddGroupServiceRoute
  '/_protected/admin/create-group': typeof ProtectedAdminCreateGroupRoute
  '/_protected/admin/create-user': typeof ProtectedAdminCreateUserRoute
  '/_protected/admin/view-groups': typeof ProtectedAdminViewGroupsRoute
  '/_protected/admin/view-users': typeof ProtectedAdminViewUsersRoute
  '/_public/auth/login': typeof PublicAuthLoginRoute
  '/_public/auth/registration/$registrationId': typeof PublicAuthRegistrationRegistrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/logout'
    | '/register-service'
    | '/view-profile'
    | '/view-services'
    | '/admin/add-group-member'
    | '/admin/add-group-service'
    | '/admin/create-group'
    | '/admin/create-user'
    | '/admin/view-groups'
    | '/admin/view-users'
    | '/auth/login'
    | '/auth/registration/$registrationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/logout'
    | '/register-service'
    | '/view-profile'
    | '/view-services'
    | '/admin/add-group-member'
    | '/admin/add-group-service'
    | '/admin/create-group'
    | '/admin/create-user'
    | '/admin/view-groups'
    | '/admin/view-users'
    | '/auth/login'
    | '/auth/registration/$registrationId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/dashboard'
    | '/_protected/logout'
    | '/_protected/register-service'
    | '/_protected/view-profile'
    | '/_protected/view-services'
    | '/_protected/admin/add-group-member'
    | '/_protected/admin/add-group-service'
    | '/_protected/admin/create-group'
    | '/_protected/admin/create-user'
    | '/_protected/admin/view-groups'
    | '/_protected/admin/view-users'
    | '/_public/auth/login'
    | '/_public/auth/registration/$registrationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicAuthLoginRoute: typeof PublicAuthLoginRoute
  PublicAuthRegistrationRegistrationIdRoute: typeof PublicAuthRegistrationRegistrationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/view-services': {
      id: '/_protected/view-services'
      path: '/view-services'
      fullPath: '/view-services'
      preLoaderRoute: typeof ProtectedViewServicesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/view-profile': {
      id: '/_protected/view-profile'
      path: '/view-profile'
      fullPath: '/view-profile'
      preLoaderRoute: typeof ProtectedViewProfileRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/register-service': {
      id: '/_protected/register-service'
      path: '/register-service'
      fullPath: '/register-service'
      preLoaderRoute: typeof ProtectedRegisterServiceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/logout': {
      id: '/_protected/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof ProtectedLogoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/auth/login': {
      id: '/_public/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof PublicAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/admin/view-users': {
      id: '/_protected/admin/view-users'
      path: '/admin/view-users'
      fullPath: '/admin/view-users'
      preLoaderRoute: typeof ProtectedAdminViewUsersRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/view-groups': {
      id: '/_protected/admin/view-groups'
      path: '/admin/view-groups'
      fullPath: '/admin/view-groups'
      preLoaderRoute: typeof ProtectedAdminViewGroupsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/create-user': {
      id: '/_protected/admin/create-user'
      path: '/admin/create-user'
      fullPath: '/admin/create-user'
      preLoaderRoute: typeof ProtectedAdminCreateUserRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/create-group': {
      id: '/_protected/admin/create-group'
      path: '/admin/create-group'
      fullPath: '/admin/create-group'
      preLoaderRoute: typeof ProtectedAdminCreateGroupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/add-group-service': {
      id: '/_protected/admin/add-group-service'
      path: '/admin/add-group-service'
      fullPath: '/admin/add-group-service'
      preLoaderRoute: typeof ProtectedAdminAddGroupServiceRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin/add-group-member': {
      id: '/_protected/admin/add-group-member'
      path: '/admin/add-group-member'
      fullPath: '/admin/add-group-member'
      preLoaderRoute: typeof ProtectedAdminAddGroupMemberRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_public/auth/registration/$registrationId': {
      id: '/_public/auth/registration/$registrationId'
      path: '/auth/registration/$registrationId'
      fullPath: '/auth/registration/$registrationId'
      preLoaderRoute: typeof PublicAuthRegistrationRegistrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedLogoutRoute: typeof ProtectedLogoutRoute
  ProtectedRegisterServiceRoute: typeof ProtectedRegisterServiceRoute
  ProtectedViewProfileRoute: typeof ProtectedViewProfileRoute
  ProtectedViewServicesRoute: typeof ProtectedViewServicesRoute
  ProtectedAdminAddGroupMemberRoute: typeof ProtectedAdminAddGroupMemberRoute
  ProtectedAdminAddGroupServiceRoute: typeof ProtectedAdminAddGroupServiceRoute
  ProtectedAdminCreateGroupRoute: typeof ProtectedAdminCreateGroupRoute
  ProtectedAdminCreateUserRoute: typeof ProtectedAdminCreateUserRoute
  ProtectedAdminViewGroupsRoute: typeof ProtectedAdminViewGroupsRoute
  ProtectedAdminViewUsersRoute: typeof ProtectedAdminViewUsersRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedLogoutRoute: ProtectedLogoutRoute,
  ProtectedRegisterServiceRoute: ProtectedRegisterServiceRoute,
  ProtectedViewProfileRoute: ProtectedViewProfileRoute,
  ProtectedViewServicesRoute: ProtectedViewServicesRoute,
  ProtectedAdminAddGroupMemberRoute: ProtectedAdminAddGroupMemberRoute,
  ProtectedAdminAddGroupServiceRoute: ProtectedAdminAddGroupServiceRoute,
  ProtectedAdminCreateGroupRoute: ProtectedAdminCreateGroupRoute,
  ProtectedAdminCreateUserRoute: ProtectedAdminCreateUserRoute,
  ProtectedAdminViewGroupsRoute: ProtectedAdminViewGroupsRoute,
  ProtectedAdminViewUsersRoute: ProtectedAdminViewUsersRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicAuthLoginRoute: PublicAuthLoginRoute,
  PublicAuthRegistrationRegistrationIdRoute:
    PublicAuthRegistrationRegistrationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
